# Generated by Django 3.2.4 on 2021-07-04 22:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=30)),
                ('postcode', models.IntegerField(validators=[django.core.validators.MinLengthValidator(4, 'Postcode must contain 4 digits.'), django.core.validators.MaxLengthValidator(4, 'Postcode must contain 4 digits.')])),
                ('vat_status', models.BooleanField()),
                ('vat_number', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^BG[0-9]{9}$', 'Your VAT number must be in the following format: BG123456789')])),
                ('eik_number', models.IntegerField(validators=[django.core.validators.MinLengthValidator(9, 'EIK number must contain 9 digits.'), django.core.validators.MaxLengthValidator(9, 'EIK number must contain 9 digits.')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
